name: cloth_mask
channels:
  - defaults
  - conda-forge
  - pip
dependencies:
  - python=3.10  # Adjust the Python version as needed
  - aiofiles=24.1.0
  - annotated-types=0.7.0
  - anyio=4.4.0
  - asttokens=2.2.1
  - backcall=0.2.0
  - blinker=1.8.2
  - carvekit=4.1.2
  - certifi=2024.7.4
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.1.4
  - debugpy=1.6.7.post1
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=1.2.0
  - fastapi=0.112.2
  - filelock=3.15.4
  - flask=3.0.3
  - fsspec=2024.6.1
  - h11=0.14.0
  - idna=3.8
  - ipykernel=6.25.1
  - ipython=8.14.0
  - itsdangerous=2.2.0
  - jedi=0.19.0
  - jinja2=3.1.4
  - jupyter-client=8.3.0
  - jupyter-core=5.3.1
  - loguru=0.7.2
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.6
  - mkl-fft=1.3.8
  - mkl-random=1.2.4
  - mkl-service=2.4.0
  - mpmath=1.3.0
  - nest-asyncio=1.5.7
  - networkx=3.3
  - numpy=1.26.4
  - opencv-python=4.10.0.84
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.39
  - pure-eval=0.2.2
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pygments=2.16.1
  - python-multipart=0.0.9
  - pywin32=306
  - pyzmq=25.1.1
  - requests=2.32.3
  - setuptools=72.1.0
  - sniffio=1.3.1
  - stack-data=0.6.2
  - starlette=0.38.2
  - sympy=1.13.2
  - torch=2.4.0
  - torchvision=0.19.0
  - tornado=6.3.3
  - tqdm=4.66.5
  - traitlets=5.9.0
  - typing=3.7.4.3
  - typing-extensions=4.12.2
  - urllib3=2.2.2
  - uvicorn=0.30.6
  - wcwidth=0.2.6
  - werkzeug=3.0.4
  - wheel=0.43.0
  - win32-setctime=1.1.0
