name: deep_learning
channels:
  - defaults
  - conda-forge
  - pip
dependencies:
  - python=3.10  # Adjust the Python version as needed
  - absl-py=1.4.0
  - aiofiles=24.1.0
  - annotated-types=0.7.0
  - anyio=4.4.0
  - asttokens=2.2.1
  - astunparse=1.6.3
  - attrs=23.1.0
  - backcall=0.2.0
  - blinker=1.8.2
  - brotli=1.0.9
  - cachetools=5.3.2
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.1.4
  - configargparse=1.7
  - contourpy=1.2.0
  - cycler=0.12.1
  - dash=2.17.1
  - dash-core-components=2.0.0
  - dash-html-components=2.0.0
  - dash-table=5.0.0
  - debugpy=1.6.7.post1
  - decorator=5.1.1
  - dill=0.3.7
  - exceptiongroup=1.2.2
  - executing=1.2.0
  - farama-notifications=0.0.4
  - fastapi=0.112.2
  - fastjsonschema=2.20.0
  - filelock=3.13.1
  - flask=3.0.3
  - flatbuffers=23.5.26
  - fonttools=4.47.0
  - fsspec=2023.12.2
  - future=0.18.3
  - gast=0.4.0
  - gmpy2=2.1.2
  - google-auth=2.25.2
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - googleapis-common-protos=1.62.0
  - grpcio=1.60.0
  - gymnasium=0.28.1
  - h11=0.14.0
  - h5py=3.10.0
  - huggingface-hub=0.20.1
  - idna=3.6
  - imageio=2.33.1
  - importlib-metadata=8.4.0
  - intel-openmp=2021.4.0
  - ipykernel=6.25.1
  - ipython=8.14.0
  - ipywidgets=8.1.3
  - itsdangerous=2.2.0
  - jax=0.4.31
  - jax-jumpy=1.0.0
  - jaxlib=0.4.31
  - jedi=0.19.0
  - jinja2=3.1.4
  - joblib=1.3.2
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jupyter-client=8.3.0
  - jupyter-core=5.3.1
  - jupyterlab-widgets=3.0.11
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.5
  - libclang=16.0.6
  - loguru=0.7.2
  - markdown=3.5.1
  - markupsafe=2.1.3
  - matplotlib=3.7.1
  - matplotlib-inline=0.1.6
  - mediapipe=0.10.14
  - mkl=2021.4.0
  - mkl-fft=1.3.1
  - mkl-random=1.2.2
  - mkl-service=2.4.0
  - ml-dtypes=0.4.0
  - mpmath=1.3.0
  - nbformat=5.10.4
  - nest-asyncio=1.5.7
  - networkx=3.2.1
  - ninja=1.11.1.1
  - numpy=2.1.0
  - oauthlib=3.2.2
  - open3d=0.18.0
  - opencv-contrib-python=4.8.1.78
  - opencv-python=4.10.0.84
  - opt-einsum=3.3.0
  - packaging=23.2
  - pandas=1.5.3
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.3.1
  - platformdirs=3.10.0
  - plotly=5.23.0
  - promise=2.3
  - prompt-toolkit=3.0.39
  - protobuf=3.19.6
  - psutil=5.9.7
  - pure-eval=0.2.2
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pydot=1.4.2
  - pygments=2.16.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python-dateutil=2.8.2
  - python-multipart=0.0.9
  - pytz=2023.3.post1
  - pywin32=306
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - referencing=0.35.1
  - regex=2023.10.3
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - retrying=1.3.4
  - rpds-py=0.20.0
  - rsa=4.9
  - scikit-learn=1.3.0
  - scipy=1.11.4
  - seaborn=0.13.2
  - setuptools=72.2.0
  - six=1.16.0
  - sniffio=1.3.1
  - sounddevice=0.4.6
  - stack-data=0.6.2
  - starlette=0.38.2
  - sympy=1.12
  - tbb=2021.13.1
  - tenacity=9.0.0
  - tensorboard=2.10.1
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.10.0
  - tensorflow-datasets=1.2.0
  - tensorflow-estimator=2.10.0
  - tensorflow-io-gcs-filesystem=0.31.0
  - tensorflow-metadata=1.13.0
  - termcolor=2.4.0
  - threadpoolctl=3.2.0
  - tokenizers=0.13.3
  - torch=2.3.1
  - torchaudio=2.3.1
  - torchgeometry=0.1.2
  - torchvision=0.18.1
  - tornado=6.3.3
  - tqdm=4.66.5
  - traitlets=5.9.0
  - transformers=4.29.2
  - typing=3.7.4.3
  - typing-extensions=4.11.0
  - urllib3=2.1.0
  - uvicorn=0.30.6
  - wcwidth=0.2.6
  - werkzeug=3.0.1
  - wheel=0.41.2
 
